name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: hypercodec/shuttle-deploy@latest
        with:
          api_key: ${{ secrets.SHUTTLE_API_KEY }}